name: LintChecks

on: [push, pull_request, workflow_dispatch]

jobs:

  PHPlint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2.1.0
      - name: Fetch PHPlint
        run: composer install
      - name: Execute PHPlint
        run: ./vendor/bin/phplint ./ --exclude=vendor --no-cache
