name: PHPStan

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: "Static Analysis"

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version:
          - "7.4"

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@master
        with:
          path: assets/ commands/ components/ config/ controllers/ mail/ messages/ migrations/ models/ modules/ views/ web/ widgets/
          php_version: "${{ matrix.php-version }}"
          autoload_file: vendor/yiisoft/yii2/Yii.php
          memory_limit: 512M
