name: PHPStan

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: "Static Analysis"

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@master
        with:
          path: views/ controllers/ modules/ models/
          php_version: "${{ matrix.php-version }}"
